### ISSUE TITLE
Thumbnail generation fails if the filename contains a non-ASCII character

### ISSUE THREAD

**Issue by alex-taylor** [tcobbs/ldview#29] opened 2020-06-27 15:47 UTC
This appears to be a recent change, as it was working in 4.3.  I've tested with a clean checkout of the current development code, and filenames with the characters '×' (hex 0xD7) and 'é' (hex 0xC3) do not get thumbnailed.  Removing the characters resolves the issue.

**Comment by tcobbs** [comment] 2020-06-28 04:50
@alex-taylor What platform (Windows, Linux, macOS)?

**Comment by alex-taylor** [comment] 2020-06-28 04:55
Windows 10

**Comment by tcobbs** [comment] 2020-06-28 07:12
@alex-taylor I'm not having any luck reproducing the problem. The following command line works for me with LDView 4.4 Alpha 6 on Windows 10 version 1909:

"C:\Program Files\LDView\LDView64.exe" -SaveSnapshots=1 ×.ldr

Can you provide an exact command line that is failing? (Note: I'll simply rename one of my existing files to match, so I don't need your model.) Also, are you using cmd.exe as your shell, or something else?

**Comment by alex-taylor** [comment] 2020-06-28 09:50
Interesting - it works if you run from the cmdline as above.  It's just thumbnail generation via Explorer that isn't working.

I rebuilt the LDViewThumbs64.dll as well, so I should be fully up to date.

**Comment by tcobbs** [comment] 2020-06-29 06:42
There were a few problems with the handling of Unicode filenames in LDViewThumbs. Hopefully they are all now fixed.

Minor note: LDViewThumbs.dll (the 32-bit version) gets uses on 64-bit Windows when using standard open and save dialogs inside 32-bit apps. LDViewThumbs64.dll gets used everywhere else on 64-bit Windows. So, if you only locally build LDViewThumbs64.dll, you can still see the problem in 32-bit open and save dialogs.

Also, regsvr32 can be run on LDViewThumbs.dll and LDViewThumbs64.dll, but once LDViewThumbs64.dll has been loaded into Windows Explorer, you probably have to either reboot, or kill and restart explorer.exe to have the new one kick in.

**Closed by tcobbs** 2020-06-29 06:42 UTC

**Comment by alex-taylor** [comment] 2020-06-29 11:09
There's a stray call to logToFile() in CLDViewThumbExtractor::findLDView which causes a compilation failure.

**Comment by tcobbs** [comment] 2020-06-29 17:04
Sorry about that. It should be fixed now.
