### ISSUE TITLE
Curve smoothing causes a shading error on part 88293

### ISSUE THREAD

**Issue by alex-taylor** [tcobbs/ldview#35] opened 2020-10-03 14:39 UTC
![10269 - Harley-Davidson Fat Boy1](https://user-images.githubusercontent.com/5150717/94994253-669d1e80-058e-11eb-8f06-03790f487a2b.png)
![10269 - Harley-Davidson Fat Boy2](https://user-images.githubusercontent.com/5150717/94994285-8e8c8200-058e-11eb-910d-a2acc704600a.png)

**Comment by tcobbs** [comment] 2021-05-06 21:52
The root cause of the problem here is that the part uses a torus primitive for the curved section, and that torus primitive includes conditional lines at its edge so that if it is placed against another torus the two will smooth together. The only way to fix this was to either decrease the max angle for smoothing (which would almost certainly result in other parts not being smoothed when they should), or to update the code to **not** smooth edges that are coincident with an edge line. I chose the latter solution, and then in fact increased the max smooth angle.

This should be fixed in this commit:

https://github.com/tcobbs/ldview/commit/98e83ee12f9237870e78fa446d73be05eb783093

Note that it only looks perfectly if primitive substitution is enabled. Since smoothing doesn't happen across parts, the surface normals at the join point slightly outward if primitive substitution is disabled.

@alex-taylor if you let me know what platform you are running on, I will provide you with a test build.

**Closed** 2021-05-06 21:53 UTC
